//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int PAG_CODIGO { get; set; }
        public int RES_CODIGO { get; set; }
        public System.DateTime PAG_FECHA { get; set; }
        public string PAG_TIPO { get; set; }
        public int TPA_CODIGO { get; set; }
        public string PAG_ESTADO { get; set; }
    }
}
